# Generated by Django 6.0.7 on 2026-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seo_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر سئو'),
        ),
    ]
