# Generated by Django 6.0.7 on 2026-08-02 14:10

from django.db import migrations, models


def invalidate_existing_challenges(apps, schema_editor):
    """Old challenges may contain six-digit codes or phone-wide lock state."""

    Otp = apps.get_model("accounts", "Otp")
    Otp.objects.update(
        code_hash="",
        attempts=0,
        used=True,
        pending_code_hash="",
        pending_expires_at=None,
        pending_attempts=0,
        send_token=None,
        send_started_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_secure_otp_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="pending_attempts",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(
            invalidate_existing_challenges,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="otp",
            name="failure_window_started_at",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="locked_until",
        ),
        migrations.AlterField(
            model_name="otp",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="تلاش\u200cهای ناموفق کد فعلی",
            ),
        ),
    ]
