# Generated by Django 6.0.7 on 2026-08-25 15:58

from django.db import migrations, models


def clear_conflicting_seo_role(apps, schema_editor):
    """نقش‌های ناسازگارِ موجود را پیش از افزودن قید پاک می‌کند.

    پنل سئو از این پس ناحیه‌ای جداست؛ کاربری که هم مدیر فروشگاه بود و هم مدیر
    سئو، مدیر فروشگاه باقی می‌ماند و فقط پرچم سئویش برداشته می‌شود تا هیچ حساب
    موجودی دسترسی داشبوردش را از دست ندهد.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_seo_manager=True).filter(
        models.Q(is_staff=True) | models.Q(is_superuser=True)
    ).update(is_seo_manager=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_city_code_address_province_code'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            clear_conflicting_seo_role, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_seo_manager', False), models.Q(('is_staff', False), ('is_superuser', False)), _connector='OR'), name='accounts_user_seo_role_exclusive'),
        ),
    ]
