# Generated by Django 6.0.7 on 2026-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seo_role_exclusive'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager_admin',
            field=models.BooleanField(default=False, verbose_name='مدیر اجرایی'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_manager_admin', False), models.Q(('is_staff', True), ('is_superuser', False)), _connector='OR'), name='accounts_user_manager_role_consistent'),
        ),
    ]
