# Generated by Django 6.0.7 on 2026-08-27 10:06

from django.db import migrations, models

# افزودن توانایی «دسترسی سئوی مدیر اجرایی».
#
# مهاجرت داده لازم نیست: فیلد با default=False اضافه می‌شود، پس هیچ حساب
# موجودی دسترسی تازه‌ای نمی‌گیرد و قید جدید هم روی همه‌ی رکوردهای فعلی
# (can_access_seo=False) بی‌درنگ برقرار است. دادن این دسترسی فقط با اقدام
# صریح سوپریوزر انجام می‌شود.
#
# نقش‌های موجود دست‌نخورده می‌مانند: سوپریوزرها سوپریوزر، مدیران اجرایی مدیر
# اجرایی، staffهای ساده «مدیر عادی» و مدیران سئو مدیر سئو.


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_manager_admin_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_seo',
            field=models.BooleanField(default=False, verbose_name='دسترسی سئوی مدیر اجرایی'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('can_access_seo', False), ('is_manager_admin', True), _connector='OR'), name='accounts_user_seo_access_manager_only'),
        ),
    ]
