# Generated by Django 6.0.7 on 2026-08-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_product_best_seller_position_product_is_best_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='تصویر')),
                ('theme', models.CharField(choices=[('brand', 'سبز (برند)'), ('secondary', 'آبی'), ('accent', 'طلایی')], default='brand', max_length=20, verbose_name='پس\u200cزمینه')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='لینک مقصد')),
                ('link_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('banner', 'بنر'), ('categories', 'دسته\u200cبندی\u200cها'), ('brands', 'برندها'), ('best_sellers', 'پرفروش\u200cترین\u200cها'), ('discounted_products', 'تخفیف\u200cهای ویژه'), ('new_products', 'جدیدترین محصولات'), ('product_collection', 'مجموعه محصولات سفارشی')], max_length=32, verbose_name='نوع بخش')),
                ('title', models.CharField(blank=True, help_text='در صورت خالی بودن، عنوان پیش\u200cفرض همان نوع بخش استفاده می\u200cشود', max_length=150, verbose_name='عنوان (اختیاری)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort', models.CharField(blank=True, choices=[('newest', 'newest'), ('cheapest', 'cheapest'), ('expensive', 'expensive'), ('popular', 'popular'), ('featured', 'featured')], max_length=20, verbose_name='مرتب\u200cسازی')),
                ('limit', models.PositiveSmallIntegerField(blank=True, help_text='خالی = پیش\u200cفرض این نوع بخش', null=True, verbose_name='حداکثر تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='homepage.banner', verbose_name='بنر')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['position', 'id'],
            },
        ),
    ]
