# Generated by Django 6.0.7 on 2026-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_recently_viewed_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('banner', 'بنر'), ('categories', 'دسته\u200cبندی\u200cها'), ('brands', 'برندها'), ('best_sellers', 'پرفروش\u200cترین\u200cها'), ('incredible_products', 'شگفت\u200cانگیزها (منتخب مدیر)'), ('discounted_products', 'همه محصولات تخفیف\u200cدار'), ('new_products', 'جدیدترین محصولات'), ('product_collection', 'مجموعه محصولات سفارشی'), ('recently_viewed', 'محصولات اخیراً مشاهده\u200cشده')], max_length=32, verbose_name='نوع بخش'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='sort',
            field=models.CharField(blank=True, choices=[('newest', 'newest'), ('cheapest', 'cheapest'), ('expensive', 'expensive'), ('popular', 'popular'), ('featured', 'featured'), ('incredible', 'incredible')], max_length=20, verbose_name='مرتب\u200cسازی'),
        ),
    ]
