# Generated by Django 6.0.7 on 2026-08-25 21:30

from django.db import migrations, models
from django.db.models import Max


def add_default_all_products_section(apps, schema_editor):
    """بخش «همه محصولات» را یک‌بار به انتهای صفحه اصلی اضافه می‌کند

    این بخش پیش‌تر در کد فروشگاه ثابت بود؛ حالا مثل بقیه‌ی بخش‌ها از پنل
    مدیریت جابه‌جا/غیرفعال می‌شود، پس همان جای قبلی‌اش (انتها) ساخته می‌شود.
    """
    HomepageSection = apps.get_model("homepage", "HomepageSection")
    if HomepageSection.objects.filter(section_type="all_products").exists():
        return
    last_position = HomepageSection.objects.aggregate(value=Max("position"))["value"]
    HomepageSection.objects.create(
        section_type="all_products",
        title="",
        position=0 if last_position is None else last_position + 1,
        is_active=True,
        limit=6,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_homepagesection_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('banner', 'بنر'), ('categories', 'دسته\u200cبندی\u200cها'), ('brands', 'برندها'), ('best_sellers', 'پرفروش\u200cترین\u200cها'), ('incredible_products', 'شگفت\u200cانگیزها (منتخب مدیر)'), ('discounted_products', 'همه محصولات تخفیف\u200cدار'), ('new_products', 'جدیدترین محصولات'), ('all_products', 'همه محصولات (صفحه\u200cبندی\u200cشده)'), ('product_collection', 'مجموعه محصولات سفارشی'), ('recently_viewed', 'محصولات اخیراً مشاهده\u200cشده')], max_length=32, verbose_name='نوع بخش'),
        ),
        # برگشت‌پذیری نباید بخشی را که مدیر بعداً ویرایش کرده حذف کند
        migrations.RunPython(
            add_default_all_products_section, migrations.RunPython.noop
        ),
    ]
