# Generated by Django 6.0.7 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_banner_responsive_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('banner', 'بنر'), ('categories', 'دسته\u200cبندی\u200cها'), ('brands', 'برندها'), ('best_sellers', 'پرفروش\u200cترین\u200cها'), ('incredible_products', 'شگفت\u200cانگیزها (منتخب مدیر)'), ('discounted_products', 'همه محصولات تخفیف\u200cدار'), ('new_products', 'جدیدترین محصولات'), ('all_products', 'همه محصولات (صفحه\u200cبندی\u200cشده)'), ('product_collection', 'مجموعه محصولات سفارشی'), ('brand_products', 'محصولات یک برند'), ('category_products', 'محصولات یک دسته\u200cبندی'), ('recently_viewed', 'محصولات اخیراً مشاهده\u200cشده')], max_length=32, verbose_name='نوع بخش'),
        ),
    ]
