# Generated by Django 6.0.7 on 2026-07-14 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('emoji', models.CharField(max_length=10, verbose_name='اموجی')),
                ('sub', models.JSONField(blank=True, default=list, verbose_name='زیردسته\u200cها')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبل (تومان)')),
                ('rating', models.FloatField(default=0, verbose_name='امتیاز')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیاز')),
                ('emoji', models.CharField(max_length=10, verbose_name='اموجی')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='برچسب')),
                ('colors', models.JSONField(blank=True, null=True, verbose_name='رنگ\u200cها')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='ویژگی\u200cها')),
                ('specs', models.JSONField(blank=True, null=True, verbose_name='مشخصات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='گارانتی')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('text', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
