# Generated by Django 6.0.7 on 2026-08-02 15:41

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='emoji',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, help_text='فایل PNG یا SVG ایمن، حداکثر ۵ مگابایت', upload_to='categories/icons/', validators=[catalog.validators.validate_category_icon], verbose_name='آیکن'),
        ),
    ]
