# Generated by Django 6.0.7 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


def copy_primary_categories(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    through = Product.categories.through
    through.objects.bulk_create(
        [
            through(product_id=product_id, category_id=category_id)
            for product_id, category_id in Product.objects.values_list(
                "id", "category_id"
            )
        ],
        ignore_conflicts=True,
    )


def clear_category_assignments(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.categories.through.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="categorized_products",
                to="catalog.category",
                verbose_name="همه دسته‌بندی‌ها",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="دسته‌بندی اصلی",
            ),
        ),
        migrations.RunPython(copy_primary_categories, clear_category_assignments),
    ]
