# Generated by Django 6.0.7 on 2026-08-09

from django.db import migrations, models


def unique_child_slug(Category, using: str, parent_slug: str, index: int) -> str:
    suffix = f"-sub-{index + 1}"
    base = f"{parent_slug[: 50 - len(suffix)]}{suffix}"
    candidate = base
    counter = 2
    while Category.objects.using(using).filter(slug=candidate).exists():
        numbered_suffix = f"-{counter}"
        candidate = f"{base[: 50 - len(numbered_suffix)]}{numbered_suffix}"
        counter += 1
    return candidate


def convert_subcategory_names(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    using = schema_editor.connection.alias

    for parent in Category.objects.using(using).all().order_by("id"):
        if not isinstance(parent.sub, list):
            continue
        seen_titles = set()
        for index, raw_title in enumerate(parent.sub or []):
            if not isinstance(raw_title, str):
                continue
            title = str(raw_title).strip()
            if not title or title in seen_titles:
                continue
            seen_titles.add(title)
            child = Category.objects.using(using).filter(title=title).first()
            if child is None:
                child = Category.objects.using(using).create(
                    title=title,
                    slug=unique_child_slug(
                        Category, using, parent.slug, index
                    ),
                    is_active=True,
                )
            if child.pk == parent.pk:
                continue

            descendants = {child.pk}
            frontier = {child.pk}
            while frontier:
                child_ids = set(
                    Category.objects.using(using)
                    .filter(parents__id__in=frontier)
                    .exclude(id__in=descendants)
                    .distinct()
                    .values_list("id", flat=True)
                )
                descendants.update(child_ids)
                frontier = child_ids
            if parent.pk not in descendants:
                child.parents.add(parent)


def restore_subcategory_names(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    using = schema_editor.connection.alias

    for parent in Category.objects.using(using).prefetch_related("children"):
        parent.sub = [child.title for child in parent.children.all()]
        parent.save(using=using, update_fields=["sub"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                symmetrical=False,
                to="catalog.category",
                verbose_name="دسته‌بندی‌های والد",
            ),
        ),
        migrations.RunPython(convert_subcategory_names, restore_subcategory_names),
        migrations.RemoveField(
            model_name="category",
            name="sub",
        ),
    ]
