# Generated by Django 6.0.7 on 2026-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_normalized_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller_position',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب در پرفروش\u200cترین\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='نمایش در بخش «پرفروش\u200cترین\u200cها» — مستقل از آمار فروش واقعی', verbose_name='پرفروش ویژه (انتخاب مدیر)'),
        ),
    ]
