# Generated by Django 6.0.7 on 2026-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='incredible_position',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب در شگفت\u200cانگیزها'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_incredible',
            field=models.BooleanField(default=False, help_text='نمایش در بخش «شگفت\u200cانگیزها» — انتخاب دستی مدیر، مستقل از تخفیف', verbose_name='شگفت\u200cانگیز ویژه (انتخاب مدیر)'),
        ),
    ]
