# Generated by Django 6.0.7 on 2026-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_incredible_position_product_is_incredible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='متن بازگشت کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='متن ارسال'),
        ),
    ]
