# Generated by Django 6.0.7 on 2026-08-18 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about', 'درباره ما'), ('contact', 'تماس با ما'), ('support', 'پاسخ به پرسش\u200cها'), ('shipping', 'رویه ارسال سفارش'), ('returns', 'شرایط بازگشت کالا'), ('how-to-order', 'نحوه ثبت سفارش'), ('track-order', 'رهگیری سفارش'), ('warranty', 'گارانتی محصولات')], max_length=40, unique=True, verbose_name='شناسه صفحه')),
                ('content', models.JSONField(verbose_name='محتوا')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_static_pages', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر')),
            ],
            options={
                'verbose_name': 'محتوای صفحه',
                'verbose_name_plural': 'محتوای صفحات',
                'constraints': [models.CheckConstraint(condition=models.Q(('key__in', ('about', 'contact', 'support', 'shipping', 'returns', 'how-to-order', 'track-order', 'warranty'))), name='staticpages_supported_key')],
            },
        ),
    ]
