# Generated by Django 6.0.7 on 2026-08-18 18:00

from django.db import migrations, models


SECTION_IDS = {
    "about": ("hero", "story", "values", "journey", "closing"),
    "contact": ("hero", "ways", "topics", "faq-promo"),
    "support": (
        "hero",
        "faq-order",
        "faq-payment",
        "faq-shipping",
        "faq-return",
        "faq-warranty",
        "faq-account",
        "contact",
    ),
    "shipping": ("hero", "steps", "checklist", "faqs", "cta", "aside"),
    "returns": ("hero", "steps", "checklist", "faqs", "cta", "aside"),
    "how-to-order": ("hero", "steps", "checklist", "faqs", "cta", "aside"),
    "track-order": ("hero", "steps", "checklist", "faqs", "cta", "aside"),
    "warranty": ("hero", "steps", "checklist", "faqs", "cta", "aside"),
}


def seed_visibility(apps, schema_editor):
    StaticPage = apps.get_model("staticpages", "StaticPage")
    database = schema_editor.connection.alias
    for key, section_ids in SECTION_IDS.items():
        StaticPage.objects.using(database).filter(key=key).update(
            is_visible=True,
            section_visibility={section_id: True for section_id in section_ids},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("staticpages", "0002_seed_static_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="نمایش صفحه"),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="section_visibility",
            field=models.JSONField(default=dict, verbose_name="نمایش بخش‌ها"),
        ),
        migrations.RunPython(seed_visibility, migrations.RunPython.noop),
    ]
