# Generated by Django 6.0.7 on 2026-07-14 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('CANCELED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام تحویل\u200cگیرنده')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('items_price', models.PositiveIntegerField(verbose_name='جمع قیمت کالاها')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('shipping_price', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبل')),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
