# Generated by Django 6.0.7 on 2026-08-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_code',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True, verbose_name='کد رسمی شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='province_code',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True, verbose_name='کد رسمی استان'),
        ),
    ]
