# Generated by Django 6.0.7 on 2026-09-06 14:57

import contacts.validation
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('footer', '0005_seed_default_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingContactButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('platform', models.CharField(default='custom', max_length=40, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]*$', 'شناسه پلتفرم معتبر نیست')], verbose_name='پلتفرم')),
                ('phone_number', models.CharField(blank=True, max_length=40, verbose_name='شماره تماس')),
                ('username', models.CharField(blank=True, max_length=500, verbose_name='نام کاربری یا نشانی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('url', models.CharField(blank=True, max_length=1000, verbose_name='نشانی دلخواه')),
                ('icon', models.FileField(blank=True, upload_to='contacts/icons/', validators=[contacts.validation.validate_contact_icon], verbose_name='آیکن آپلودی')),
                ('icon_name', models.CharField(blank=True, max_length=40, verbose_name='آیکن پیش\u200cفرض انتخابی')),
                ('tooltip_text', models.CharField(blank=True, max_length=200, verbose_name='راهنما')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='باز شدن در تب جدید')),
                ('position', models.CharField(choices=[('bottom-right', 'پایین راست'), ('bottom-left', 'پایین چپ')], default='bottom-right', max_length=20, verbose_name='محل نمایش')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_buttons', to='footer.footericon', verbose_name='آیکن کتابخانه')),
            ],
            options={
                'verbose_name': 'دکمه تماس شناور',
                'verbose_name_plural': 'دکمه\u200cهای تماس شناور',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order', 'id'], name='contact_active_order_idx')],
            },
        ),
    ]
