# Generated by Django 6.0.7 on 2026-08-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(blank=True, help_text='خالی = نام سایت از تنظیمات سئو', max_length=120, verbose_name='نام برند')),
                ('logo', models.ImageField(blank=True, upload_to='footer/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='توضیح کوتاه')),
                ('copyright_text', models.CharField(blank=True, help_text='عبارت {year} با سال جاری جایگزین می\u200cشود', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='نشانی')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='ایمیل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('variant', models.CharField(choices=[('column', 'ستون (فهرست عمودی)'), ('strip', 'نوار مزیت\u200cها (ردیف افقی بالای فوتر)')], default='column', max_length=20, verbose_name='چیدمان')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='توضیح زیر عنوان')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بخش فوتر',
                'verbose_name_plural': 'بخش\u200cهای فوتر',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['position', 'id'], name='footer_section_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('link', 'پیوند'), ('text', 'متن'), ('image', 'تصویر'), ('phone', 'شماره تماس'), ('email', 'ایمیل'), ('address', 'نشانی'), ('social', 'شبکه اجتماعی')], default='link', max_length=20, verbose_name='نوع محتوا')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='نشانی مقصد')),
                ('text', models.TextField(blank=True, max_length=600, verbose_name='متن')),
                ('image', models.ImageField(blank=True, upload_to='footer/items/', verbose_name='تصویر')),
                ('icon', models.CharField(blank=True, help_text='یک ایموجی یا نویسه\u200cی کوتاه', max_length=32, verbose_name='آیکن')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('static_page_key', models.CharField(blank=True, choices=[('about', 'درباره ما'), ('contact', 'تماس با ما'), ('support', 'پاسخ به پرسش\u200cها'), ('shipping', 'رویه ارسال سفارش'), ('returns', 'شرایط بازگشت کالا'), ('how-to-order', 'نحوه ثبت سفارش'), ('track-order', 'رهگیری سفارش'), ('warranty', 'گارانتی محصولات')], help_text='اگر مدیر آن صفحه را پنهان کند، این پیوند هم پنهان می\u200cشود', max_length=40, verbose_name='صفحه\u200cی محتوایی مرتبط')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='footer.footersection', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'محتوای فوتر',
                'verbose_name_plural': 'محتواهای فوتر',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['section', 'position', 'id'], name='footer_item_order_idx')],
            },
        ),
    ]
