# Generated by Django 6.0.7 on 2026-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_seed_current_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='بزرگ\u200cنمایی نقشه'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='maps_place_url',
            field=models.CharField(blank=True, help_text='جای\u200cگزین پیوند «مشاهده روی نقشه»؛ مسیریابی همیشه از مختصات ساخته می\u200cشود', max_length=500, verbose_name='پیوند صفحه\u200cی گوگل مپس (اختیاری)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_map',
            field=models.BooleanField(default=True, verbose_name='نمایش نقشه در فوتر'),
        ),
    ]
