# Generated by Django 6.0.7 on 2026-08-30 14:58

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_footer_shop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام')),
                ('image', models.FileField(help_text='فایل PNG یا SVG ایمن، حداکثر ۵ مگابایت', upload_to='footer/icons/', validators=[catalog.validators.validate_category_icon], verbose_name='فایل آیکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'آیکن فوتر',
                'verbose_name_plural': 'آیکن\u200cهای فوتر',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='icon',
            field=models.CharField(blank=True, help_text='وقتی آیکن تصویری انتخاب نشده باشد به کار می\u200cرود', max_length=32, verbose_name='ایموجی جایگزین'),
        ),
        migrations.AddField(
            model_name='footeritem',
            name='icon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='footer.footericon', verbose_name='آیکن'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='footer.footericon', verbose_name='آیکن نشانی'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='email_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='footer.footericon', verbose_name='آیکن ایمیل'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='phone_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='footer.footericon', verbose_name='آیکن تلفن'),
        ),
    ]
