# Generated by Django 6.0.7 on 2026-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_seed_default_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین نماد'),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='item_type',
            field=models.CharField(choices=[('link', 'پیوند'), ('text', 'متن'), ('image', 'تصویر'), ('badge', 'نماد یا مجوز'), ('phone', 'شماره تماس'), ('email', 'ایمیل'), ('address', 'نشانی'), ('social', 'شبکه اجتماعی')], default='link', max_length=20, verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='variant',
            field=models.CharField(choices=[('column', 'ستون (فهرست عمودی)'), ('strip', 'نوار مزیت\u200cها (ردیف افقی بالای فوتر)'), ('badges', 'نمادها و مجوزها')], default='column', max_length=20, verbose_name='چیدمان'),
        ),
        migrations.AddConstraint(
            model_name='footersection',
            constraint=models.UniqueConstraint(condition=models.Q(('variant', 'badges')), fields=('variant',), name='footer_single_badges_section'),
        ),
    ]
