# Generated by Django 6.0.7 on 2026-08-06 09:15

import blog.models
import blog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی وبلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای وبلاگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'برچسب وبلاگ',
                'verbose_name_plural': 'برچسب\u200cهای وبلاگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True, verbose_name='نامک')),
                ('excerpt', models.CharField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('featured_image', models.ImageField(blank=True, upload_to=blog.models.featured_image_upload_to, validators=[blog.validators.validate_featured_image], verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشرشده')], default='DRAFT', max_length=12, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سئو')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات سئو')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'نوشته وبلاگ',
                'verbose_name_plural': 'نوشته\u200cهای وبلاگ',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_public_idx'), models.Index(fields=['category', 'status', 'published_at'], name='blog_post_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('status', 'PUBLISHED')), _connector='OR'), name='blog_post_publication_state')],
            },
        ),
    ]
