# Generated by Django 6.0.7 on 2026-07-23 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True, verbose_name='مسیر')),
                ('hits', models.PositiveIntegerField(default=1, verbose_name='دفعات')),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='ارجاع\u200cدهنده')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خطای ۴۰۴',
                'verbose_name_plural': 'خطاهای ۴۰۴',
                'ordering': ['-hits'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(max_length=300, unique=True, verbose_name='از مسیر')),
                ('to_path', models.CharField(max_length=300, verbose_name='به مسیر')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 دائمی'), (302, '302 موقت')], default=301, verbose_name='کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ریدایرکت',
                'verbose_name_plural': 'ریدایرکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='آدرس')),
                ('kind', models.CharField(choices=[('page', 'صفحه'), ('link', 'لینک')], max_length=10, verbose_name='نوع')),
                ('status_code', models.PositiveSmallIntegerField(null=True, verbose_name='کد وضعیت')),
                ('response_ms', models.PositiveIntegerField(null=True, verbose_name='زمان پاسخ (ms)')),
                ('ok', models.BooleanField(default=True, verbose_name='سالم')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='زمان بررسی')),
            ],
            options={
                'verbose_name': 'نتیجه اسکن',
                'verbose_name_plural': 'نتایج اسکن',
                'ordering': ['ok', '-response_ms'],
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ابزار سبز', max_length=100, verbose_name='نام سایت')),
                ('site_url', models.CharField(default='http://localhost:3000', max_length=200, verbose_name='آدرس سایت')),
                ('default_meta_description', models.TextField(blank=True, verbose_name='توضیحات متای پیش\u200cفرض')),
                ('robots_txt', models.TextField(blank=True, verbose_name='robots.txt')),
                ('sitemap_enabled', models.BooleanField(default=True, verbose_name='سایت\u200cمپ فعال')),
                ('sitemap_include_products', models.BooleanField(default=True, verbose_name='محصولات در سایت\u200cمپ')),
                ('sitemap_include_categories', models.BooleanField(default=True, verbose_name='دسته\u200cبندی\u200cها در سایت\u200cمپ')),
                ('sitemap_include_static', models.BooleanField(default=True, verbose_name='صفحات ثابت در سایت\u200cمپ')),
                ('sitemap_excluded_paths', models.TextField(blank=True, help_text='هر مسیر در یک خط', verbose_name='مسیرهای حذف\u200cشده از سایت\u200cمپ')),
                ('breadcrumbs_enabled', models.BooleanField(default=True, verbose_name='بردکرامب + اسکیمای آن')),
                ('lazyload_enabled', models.BooleanField(default=True, verbose_name='لیزی\u200cلود تصاویر')),
                ('image_compression_enabled', models.BooleanField(default=True, verbose_name='فشرده\u200cسازی تصاویر هنگام آپلود')),
                ('org_schema_enabled', models.BooleanField(default=True, verbose_name='اسکیمای Organization')),
                ('hreflang', models.JSONField(blank=True, default=list, verbose_name='hreflang')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سئو',
                'verbose_name_plural': 'تنظیمات سئو',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('product', 'محصول'), ('category', 'دسته\u200cبندی'), ('static', 'صفحه ثابت')], max_length=20, verbose_name='نوع صفحه')),
                ('object_key', models.CharField(max_length=200, verbose_name='کلید')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, verbose_name='نامک')),
                ('canonical', models.CharField(blank=True, max_length=300, verbose_name='Canonical')),
                ('robots_index', models.BooleanField(default=True, verbose_name='index')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='follow')),
                ('focus_keyword', models.CharField(blank=True, max_length=100, verbose_name='کلمه کلیدی کانونی')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان OG')),
                ('og_description', models.TextField(blank=True, verbose_name='توضیحات OG')),
                ('og_image', models.CharField(blank=True, max_length=300, verbose_name='تصویر OG')),
                ('twitter_card', models.CharField(choices=[('summary', 'summary'), ('summary_large_image', 'summary_large_image')], default='summary_large_image', max_length=30, verbose_name='Twitter Card')),
                ('schema_type', models.CharField(blank=True, choices=[('Product', 'Product'), ('Article', 'Article'), ('FAQPage', 'FAQPage'), ('WebPage', 'WebPage'), ('CollectionPage', 'CollectionPage')], max_length=30, verbose_name='نوع اسکیما')),
                ('schema_custom', models.TextField(blank=True, help_text='در صورت تعیین، جایگزین اسکیمای خودکار می\u200cشود', verbose_name='اسکیمای سفارشی (JSON-LD)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'متای صفحه',
                'verbose_name_plural': 'متای صفحات',
                'constraints': [models.UniqueConstraint(fields=('page_type', 'object_key'), name='unique_page_meta')],
            },
        ),
        migrations.CreateModel(
            name='MetaRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='داده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='seo.pagemeta')),
            ],
            options={
                'verbose_name': 'نسخه متا',
                'verbose_name_plural': 'نسخه\u200cهای متا',
                'ordering': ['-created_at'],
            },
        ),
    ]
