# Generated by Django 6.0.7 on 2026-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='site_name',
            field=models.CharField(default='گروه صنعتی توانا', max_length=100, verbose_name='نام سایت'),
        ),
    ]
