export type FloatingContactButton = {
  id: number;
  title: string;
  platform: string;
  url: string;
  icon: string | null;
  iconName: string;
  tooltipText: string;
  openInNewTab: boolean;
  position: "bottom-right" | "bottom-left";
  displayOrder: number;
};

export const CONTACT_ICONS: Record<string, { label: string; glyph: string }> = {
  whatsapp: { label: "واتساپ", glyph: "whatsapp" },
  telegram: { label: "تلگرام", glyph: "send" },
  instagram: { label: "اینستاگرام", glyph: "instagram" },
  phone: { label: "تلفن", glyph: "phone" },
  sms: { label: "پیامک", glyph: "chat" },
  email: { label: "ایمیل", glyph: "email" },
  bale: { label: "بله", glyph: "ب" },
  eitaa: { label: "ایتا", glyph: "ا" },
  rubika: { label: "روبیکا", glyph: "cube" },
  linkedin: { label: "لینکدین", glyph: "in" },
  custom: { label: "وب‌سایت", glyph: "link" },
  chat: { label: "گفت‌وگو", glyph: "chat" },
  link: { label: "پیوند", glyph: "link" },
};

export function contactIconName(button: Pick<FloatingContactButton, "iconName" | "platform">): string {
  const name = button.iconName || button.platform;
  return Object.hasOwn(CONTACT_ICONS, name) ? name : "custom";
}

export function isStorefrontPath(pathname: string): boolean {
  return pathname !== "/admin" && !pathname.startsWith("/admin/");
}

export function contactLinkAttributes(button: FloatingContactButton) {
  // Destinations are generated by Django; this guard also protects against bad cached data.
  if (!/^(https?:\/\/|tel:|sms:|mailto:)/i.test(button.url)) return null;
  const newTab = button.openInNewTab && /^https?:\/\//i.test(button.url);
  return {
    href: button.url,
    target: newTab ? "_blank" : undefined,
    rel: newTab ? "noopener noreferrer" : undefined,
    "aria-label": button.title,
    title: button.tooltipText || undefined,
  };
}

export function groupContactButtons(buttons: FloatingContactButton[]) {
  const groups: Record<FloatingContactButton["position"], FloatingContactButton[]> = {
    "bottom-right": [],
    "bottom-left": [],
  };
  for (const button of [...buttons].sort((a, b) => a.displayOrder - b.displayOrder || a.id - b.id)) {
    if (Object.hasOwn(groups, button.position) && contactLinkAttributes(button)) {
      groups[button.position].push(button);
    }
  }
  return groups;
}

export function isContactButton(value: unknown): value is FloatingContactButton {
  if (!value || typeof value !== "object") return false;
  const button = value as Record<string, unknown>;
  return (
    typeof button.id === "number" && Number.isInteger(button.id) &&
    typeof button.title === "string" && !!button.title.trim() &&
    typeof button.platform === "string" && typeof button.url === "string" &&
    (button.icon === null || typeof button.icon === "string") &&
    typeof button.iconName === "string" && typeof button.tooltipText === "string" &&
    typeof button.openInNewTab === "boolean" &&
    (button.position === "bottom-right" || button.position === "bottom-left") &&
    typeof button.displayOrder === "number" && Number.isInteger(button.displayOrder) && button.displayOrder >= 0
  );
}
